org: null
app: null

service: portfolio-admin-upload

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    SECRET_ACCESS_KEY_PATH: ${env:SECRET_ACCESS_KEY_PATH}
    ACCESS_KEY: ${env:ACCESS_KEY}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}
    BUCKET: ${env:BUCKET}

functions:
  healthCheck:
    handler: src/handlers/handler.healthCheck
    events:
      - http:
          path: healthCheck
          method: get
          cors: true
  verifyAccessKey:
    handler: src/handlers/verifyAccessKey.verifyAccessKey
    events:
      - http:
          path: verifyAccessKey
          method: post
          cors: true
  uploadResume:
    handler: src/handlers/upload.uploadResume
    events:
      - http:
          path: uploadResume
          method: post
          cors: true
  downloadResume:
    handler: src/handlers/downloadResume.downloadResume
    events:
      - http:
          path: downloadResume
          method: get
          cors: true
plugins:
  - serverless-dotenv-plugin
